FROM --platform=$BUILDPLATFORM golang:alpine as builder

WORKDIR /app

COPY *.go ./
RUN CGO_ENABLED=0 GOOS=$TARGETOS GOARCH=$TARGETARCH go build -o /solarapi solarapi.go 

FROM ghcr.io/stefanschoof/vzlogger:nightly

COPY --from=builder ./solarapi /usr/local/bin/solarapi
