version: '3'
services:

  volkszaehler:
    image: stefanschoof/volkszaehler
    volumes:
      - ./volkszaehler.yaml:/vz/etc/config.yaml
      - ./options.js:/vz/htdocs/js/options.js
    ports:
      - 8080:8080
    # NOTE: The init command will only work once the database is fully up and running.
    #       By putting restart: always docker-compose will retry starting this container
    #       and finally complete the database setup sequence.
    command: >
      sh -c "(/vz/bin/doctrine orm:schema-tool:update --force ||
      /vz/bin/doctrine orm:schema-tool:create) && /vz/vendor/bin/ppm start -c
      /vz/etc/middleware.json --static-directory /vz/htdocs
      --cgi-path=/usr/local/bin/php --workers=1"
    networks:
      - volkszaehler
      - traefik
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.volkszaehler.loadbalancer.server.port=8080"
      - "traefik.docker.network=traefik"

  push-server:
    image: stefanschoof/volkszaehler
    volumes:
      - ./volkszaehler.yaml:/vz/etc/config.yaml
    ports:
      - 5582:5582
      - 8082:8082
    command: /vz/bin/push-server
    networks:
      - volkszaehler
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.volkszaehler-push.loadbalancer.server.port=8082"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.volkszaehler-push.rule=Host(`${HOST}`) &&
        PathPrefix(`/ws`)"

  mbmd:
    image: volkszaehler/mbmd
    volumes:
      - ./mbmd.yaml:/etc/mbmd.yaml
    command: run
    networks:
      - volkszaehler
    restart: always

  vzlogger:
    build:
      context: .
      dockerfile: Dockerfile.vzlogger
    volumes:
      - ./vzlogger.conf:/etc/vzlogger.conf
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    networks:
      - volkszaehler
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

networks:
  volkszaehler: null
  traefik:
    external: true
