version: '3'
services:

  volkszaehler:
    # image: volkszaehler/volkszaehler
    image: stefanschoof/volkszaehler
    volumes:
      - ./volkszaehler.yaml:/vz/etc/config.yaml
    ports:
      - 8080:8080
    # NOTE: The init command will only work once the database is fully up and running.
    #       By putting restart: always docker-compose will retry starting this container
    #       and finally complete the database setup sequence.
    command: >
      sh -c "(/vz/bin/doctrine orm:schema-tool:update --force ||
      /vz/bin/doctrine orm:schema-tool:create) && /vz/vendor/bin/ppm start -c
      /vz/etc/middleware.json --static-directory /vz/htdocs
      --cgi-path=/usr/local/bin/php --workers=1"
    networks:
      - volkszaehler
      - traefik
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.volkszaehler.loadbalancer.server.port=8080"
      - "traefik.docker.network=traefik"
      - "com.centurylinklabs.watchtower.monitor-only=true"

  vzlogger:
    build:
      context: .
      dockerfile: Dockerfile.vzlogger
    volumes:
      - ./vzlogger.conf:/etc/vzlogger.conf
    ports:
      - 8081:8081
    devices:
      - /dev/ttyUSBir:/dev/ttyUSB0
    networks:
      - volkszaehler
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

networks:
  volkszaehler: null
  traefik:
    external: true
