sources:
- name: mbmd
  type: homie
  url: tcp://mosquitto:1883

targets:
- name: zaehler
  type: http
  url: http://volkszaehler:8080/data/{name}.json
  method: POST
  headers:
    Content-type: application/json
    Accept: application/json
  payload: >-
    [[{timestamp:ms},{value}]]

wires:
- source: mbmd
  target: zaehler
  actions:
  - homie-to-volkszaehler

actions:
- name: homie-to-volkszaehler
  type: map
  matches:
    dcpower: 741bc3c0-dba9-11ea-8de4-9d08f2a5113c
    power: 82fcd590-dba9-11ea-b34b-014102ba3790
    export:	920911a0-dba9-11ea-981f-e7babc04fcc7

